-- ./help/quickstart-en-v2024.04.sdr/metadata.html.lua
return {
    ["bookmarks"] = {},
    ["bookmarks_sorted_20220106"] = true,
    ["bookmarks_version"] = 20200615,
    ["config_panel_index"] = 2,
    ["copt_b_page_margin"] = 15,
    ["copt_block_rendering_mode"] = 3,
    ["copt_cjk_width_scaling"] = 100,
    ["copt_embedded_css"] = 1,
    ["copt_embedded_fonts"] = 1,
    ["copt_font_base_weight"] = 0,
    ["copt_font_gamma"] = 15,
    ["copt_font_hinting"] = 2,
    ["copt_font_kerning"] = 3,
    ["copt_font_size"] = 22,
    ["copt_h_page_margins"] = {
        [1] = 10,
        [2] = 10,
    },
    ["copt_line_spacing"] = 100,
    ["copt_nightmode_images"] = 1,
    ["copt_render_dpi"] = 96,
    ["copt_rotation_mode"] = 0,
    ["copt_smooth_scaling"] = 0,
    ["copt_status_line"] = 1,
    ["copt_sync_t_b_page_margins"] = 0,
    ["copt_t_page_margin"] = 15,
    ["copt_view_mode"] = 0,
    ["copt_visible_pages"] = 1,
    ["copt_word_expansion"] = 0,
    ["copt_word_spacing"] = {
        [1] = 95,
        [2] = 75,
    },
    ["cre_dom_version"] = 20240114,
    ["css"] = "./data/epub.css",
    ["doc_pages"] = 10,
    ["doc_path"] = "./help/quickstart-en-v2024.04.html",
    ["doc_props"] = {
        ["title"] = "KOReader Quickstart Guide",
    },
    ["floating_punctuation"] = 0,
    ["font_face"] = "Noto Serif",
    ["font_family_fonts"] = {},
    ["handmade_flows_edit_enabled"] = true,
    ["handmade_flows_enabled"] = false,
    ["handmade_toc_edit_enabled"] = true,
    ["handmade_toc_enabled"] = false,
    ["hide_nonlinear_flows"] = false,
    ["highlight"] = {},
    ["highlight_drawer"] = "lighten",
    ["highlights_imported"] = true,
    ["hyph_force_algorithmic"] = false,
    ["hyph_soft_hyphens_only"] = false,
    ["hyph_trust_soft_hyphens"] = false,
    ["hyphenation"] = true,
    ["inverse_reading_order"] = false,
    ["last_xpointer"] = "/html/body/div[1]/img.0",
    ["page_overlap_style"] = "dim",
    ["partial_md5_checksum"] = "04fef225923a326a16964b7ff4afd2ee",
    ["partial_rerendering"] = true,
    ["percent_finished"] = 0.1,
    ["preferred_dictionaries"] = {},
    ["readermenu_tab_index"] = 1,
    ["show_overlap_enable"] = false,
    ["stats"] = {
        ["authors"] = "N/A",
        ["highlights"] = 0,
        ["language"] = "N/A",
        ["notes"] = 0,
        ["pages"] = 10,
        ["performance_in_pages"] = {},
        ["series"] = "N/A",
        ["title"] = "KOReader Quickstart Guide",
    },
    ["summary"] = {
        ["modified"] = "2025-01-03",
        ["status"] = "reading",
    },
    ["text_lang"] = "en-US",
    ["text_lang_embedded_langs"] = true,
    ["toc_ticks_ignored_levels"] = {},
}
