#!/bin/sh

FLAG_PATH="/mnt/SDCARD/spruce/flags"
FLAG_FILE="$FLAG_PATH/credits.lock"
MENU_FILE="$FLAG_PATH/in_menu.lock"
LONG_PRESSED=false

long_press_handler() {
    # set flag for long pressed event
    LONG_PRESSED=false
    sleep 5
    if [ -f "$MENU_FILE" ]; then
        LONG_PRESSED=true
        

        # kill MainUI
        killall -q -9 MainUI || \
        /mnt/SDCARD/miyoo/app/kill_apps.sh
        
        # set flag file for principal.sh to load credits app
        touch "$FLAG_FILE"
    fi
}

# listen to log file and handle key press events
# the keypress logs are generated by keymon
tail -F -n 1 /var/log/messages | while read line; do
    if [ -f "$MENU_FILE" ]; then
        case $line in
            *"key 1 15 1"*) # START key down
                # start long press handler
                long_press_handler &
                PID=$!
            ;;
            *"key 1 15 0"*) # START key up
                # kill the long press handler if 
                # menu button is released within time limit
                # and is in game now
                if [ "$LONG_PRESSED" = false ] ; then
                    kill $PID
                fi
            ;;
        esac
    fi
done 
