#!/bin/bash

if [[ "$BL_TYPE" == "TYPE1" ]]; then
  cat /sys/class/disp/disp/attr/sys | grep -oP 'backlight\(\s*\K\d+'
elif [[ "$BL_TYPE" == "TYPE2" ]]; then
  cat $SYSFS_BL_BRIGHTNESS
else
  echo "155"
fi