# Screen config, uncomment if having issues with autodetection or want a manual resolution
screen_width = SCREEN_W
screen_height = SCREEN_H

# Symmetric, ie: 3 = 3x3
grid_size = 3

# Images path
images_path = "/mnt/SDCARD/Saves/screenshots/"

# Key mappings, see https://www.libsdl.org/release/SDL-1.2.15/include/SDL_keysym.h
key_up = 273
key_down = 274
key_right = 275
key_left = 276
key_accept = 32
key_cancel =306
key_select = 13
key_next = 116
key_prev = 101
key_zoom_in = 304
key_zoom_out = 308
key_exit = 13
