# Screen config, uncomment if having issues with autodetection or want a manual resolution
screen_width = SCREEN_W
screen_height = SCREEN_H

# Symmetric, ie: 3 = 3x3
grid_size = 3

# Images path
images_path = "/mnt/SDCARD/Saves/screenshots/"

# Key mappings, see https://www.libsdl.org/release/SDL-1.2.15/include/SDL_keysym.h
key_up = 273
key_down = 274
key_right = 275
key_left = 276
key_accept = 13
key_cancel = 8
key_select = 127
key_next = 281
key_prev = 280
key_zoom_in = 282
key_zoom_out = 283
key_help = 104
key_exit = 27

# Button labels (for the help screen), copy from controllerbuttons.html in the res/ folder
label_dpad = ""
label_accept = ""
label_cancel = ""
label_select = "start"
label_next = ""
label_prev = ""
label_zoom_in = ""
label_zoom_out = ""
label_exit = "menu"
