#!/bin/sh

. /mnt/SDCARD/spruce/scripts/helperFunctions.sh

BIN_PATH="/mnt/SDCARD/spruce/bin"

LONG_PRESSED=false

long_press_handler() {

    flag_add "credits.longpress"
    sleep 5
    flag_remove "credits.longpress"

    if flag_check "in_menu"; then
        # kill MainUI
        killall -q -9 MainUI || \
        /mnt/SDCARD/miyoo/app/kill_apps.sh
        
        # set flag file for principal.sh to load credits app
        flag_add "credits"
    fi
}

# listen to log file and handle key press events
# the keypress logs are generated by keymon
$BIN_PATH/getevent /dev/input/event3 | while read line; do
    case $line in
        *"$B_L1 1"*) # L1 key down
            if flag_check "in_menu"; then
                # always try to kill old handler and start new long press handler
                kill $PID 2> /dev/null
                long_press_handler &
                PID=$!
            fi
        ;;
        *"$B_L1 0"*) # L1 key up
            # kill the long press handler if 
            # menu button is released within time limit
            # and is in game now
            if flag_check "credits.longpress" ; then
                flag_remove "credits.longpress"
                kill $PID
            fi
        ;;
    esac
done
