#!/bin/sh

. /mnt/SDCARD/spruce/scripts/helperFunctions.sh
# Shared button-action dispatch (perform_action, kill_emulator,
# prepare_game_switcher, pause_drastic/resume_drastic, ...). Also sourced by
# buttons_watchdog.sh for the top Home button on devices that have one.
. /mnt/SDCARD/spruce/scripts/button_actions.sh

log_message "homebutton_watchdog.sh: Started up."

RETROARCH_CFG="/mnt/SDCARD/RetroArch/retroarch.cfg"

SCREENSHOT_SHORTCUT="$(get_config_value '.menuOptions."System Settings".globalScreenshotShortcut.selected' "L2+R2+Y")"
SELECT_DOWN=false

cancel_menu_hold() {
    # If the menu button is currently held, cancel both tap and hold
    if [ -e /tmp/menubtn ]; then
        touch /tmp/menubtn_cancelled
        if [ -n "$menu_hold_pid" ]; then
            kill "$menu_hold_pid" 2>/dev/null
            wait "$menu_hold_pid" 2>/dev/null
            menu_hold_pid=""
        fi
    fi
}



home_key_down () {

    if [ ! -e /tmp/menubtn ]; then
        pause_drastic
        menu_btn_press_time=$(date +%s)
        log_message "Menu button pressed at $menu_btn_press_time" 
        touch /tmp/menubtn

        # Launch background timer that waits required seconds, then triggers the action
        (
            menu_hold_time=$(get_config_value '.menuOptions."Game Switcher Settings".menuHoldTime.selected' 2)
            sleep "$menu_hold_time"
            # Check if the menubtn file still exists (i.e. button still held) AND NOT cancelled (i.e. no other button pressed)
            if [ -e /tmp/menubtn ] && [ ! -e /tmp/menubtn_cancelled ]; then
                rm -f /tmp/menubtn
                rm -f /tmp/menubtn_cancelled
                do_vibrate="$(get_config_value '.menuOptions."Game Switcher Settings".menuShouldVibrate.selected' "True")"
                # Only vibrate if enabled
                if [ "$do_vibrate" = "True" ]; then
                    vibrate &
                fi
                HOLD_HOME="$(get_config_value '.menuOptions."Emulator Settings".holdHomeAction.selected' "Game Switcher")"
                log_message "homebutton_watchdog.sh: Performing hold-home action: $HOLD_HOME"
                perform_action "$HOLD_HOME"

                # Only clean up game state when the action actually killed the game.
                # "Emulator menu" just opens an in-game menu — the game is still running.
                if [ "$HOLD_HOME" != "Emulator menu" ]; then
                    rm -f /tmp/cmd_to_run.sh
                    rm -f /mnt/SDCARD/spruce/flags/lastgame.lock
                fi

            fi
        ) &
        menu_hold_pid=$!
    fi
}

home_key_up () {
    log_message "Menu button released at $(date +%s)"  
    if [ -e /tmp/menubtn ]; then
        rm -f /tmp/menubtn

        was_cancelled=false
        if [ -e /tmp/menubtn_cancelled ]; then
            was_cancelled=true
            rm -f /tmp/menubtn_cancelled
        fi

        # Kill background hold timer if still running
        if [ -n "$menu_hold_pid" ]; then
            kill "$menu_hold_pid" 2>/dev/null
            wait "$menu_hold_pid" 2>/dev/null
            menu_hold_pid=""
        fi

        if [ "$was_cancelled" = false ]; then
            TAP_HOME="$(get_config_value '.menuOptions."Emulator Settings".tapHomeAction.selected' "Emulator menu")"
            log_message "homebutton_watchdog.sh: Performing tap-home action: $TAP_HOME"
            perform_action "$TAP_HOME"
        fi

        resume_drastic
    fi

}


# listen to log file and handle key press events
# the keypress logs are generated by keymon
getevent -pid $$ $EVENT_PATH_READ_INPUTS_SPRUCE | while read line; do
    log_message "homebutton_watchdog.sh: $line" -v

    case $line in
        # Home key down
        *"key $B_MENU 1"*)
                if [ "$SCREENSHOT_SHORTCUT" != "MENU+SELECT" ] || [ "$SELECT_DOWN" = false ]; then
                    home_key_down
                fi
            ;;

        # Home key up
        *"key $B_MENU 0"*)
                home_key_up
            ;;

        *"key $B_SELECT 1"*)
            SELECT_DOWN=true
            cancel_menu_hold
            resume_drastic
            ;;

        *"key $B_SELECT 0"*)
            SELECT_DOWN=false
            ;;

        *"key $B_START 1"*  | \
        *"key $B_R1"*      | \
        *"key $B_R2"*      | \
        *"key $B_L1"*      | \
        *"key $B_L2"*      | \
        *"key $B_A 1"*     | \
        *"key $B_B 1"*     | \
        *"key $B_X 1"*     | \
        *"key $B_Y 1"*     | \
        *"key $B_VOLUP 1"* | \
        *"key $B_VOLDOWN 1"* | \
        *"key $B_LEFT"*    | \
        *"key $B_RIGHT"*   | \
        *"key $B_UP"*      | \
        *"key $B_DOWN"* )
            cancel_menu_hold
            resume_drastic
            ;;
        esac
done

