from enum import Enum, auto

class ControllerInput(Enum):
    A = auto()
    B = auto()
    X = auto()
    Y = auto()
    MENU = auto()
    DPAD_UP = auto()
    DPAD_DOWN = auto()
    DPAD_LEFT = auto()
    DPAD_RIGHT = auto()
    L1 = auto()
    L2 = auto()
    L3 = auto()
    R1 = auto()
    R2 = auto()
    R3 = auto()
    START = auto()
    SELECT = auto()
    LEFT_STICK_UP = auto()
    LEFT_STICK_DOWN = auto()
    LEFT_STICK_LEFT = auto()
    LEFT_STICK_RIGHT = auto()
    RIGHT_STICK_UP = auto()
    RIGHT_STICK_DOWN = auto()
    RIGHT_STICK_LEFT = auto()
    RIGHT_STICK_RIGHT = auto()
    VOLUME_DOWN = auto()
    VOLUME_UP = auto()
    POWER_BUTTON = auto()
    UNKNOWN = auto()
