#!/bin/sh

INFO=$(cat /proc/cpuinfo 2> /dev/null)
case $INFO in
    *"sun8i"*) export PLATFORM="A30" ;;
    *"TG5040"*)	export PLATFORM="SmartPro" ;;
    *"TG3040"*)	export PLATFORM="Brick"	;;
    *"TG5050"*)	export PLATFORM="SmartProS"	;;
    *"TG4040"*)	export PLATFORM="BrickPro"	;;
    *"0xd05"*)
        # Flip and Miniloong Pocket 1 share the part id; see helperFunctions.sh.
        if [ -x /loong/loong_daemon ]; then
            export PLATFORM="Miniloong"
        else
            export PLATFORM="Flip"
        fi
        ;;
    *"0xd04"*) export PLATFORM="Pixel2" ;;
    *) 
        if [ -e /usr/magicx ]; then
            export PLATFORM="Zero28"
        else
            export PLATFORM="MiyooMini" 
        fi
        ;;
esac


if [ "$PLATFORM" = "MiyooMini" ]; then
    /mnt/SDCARD/spruce/scripts/platform/miyoo_mini_startup.sh
else
    cd /mnt/SDCARD/spruce/scripts
    ./runtime.sh
fi
