#!/bin/sh

INFO=$(cat /proc/cpuinfo 2> /dev/null)
case $INFO in
    *"sun8i"*) export PLATFORM="A30" ;;
    *"TG5040"*)	export PLATFORM="SmartPro" ;;
    *"TG3040"*)	export PLATFORM="Brick"	;;
    *"TG5050"*)	export PLATFORM="SmartProS"	;;
    *"0xd05"*) export PLATFORM="Flip" ;;
    *"0xd04"*) export PLATFORM="Pixel2" ;;
    *) export PLATFORM="MiyooMini" ;;
esac


if [ "$PLATFORM" = "MiyooMini" ]; then
    /mnt/SDCARD/spruce/scripts/platform/miyoo_mini_startup.sh
else
    cd /mnt/SDCARD/spruce/scripts
    ./runtime.sh
fi
